In [1]:
import json
import pandas as pd

In [2]:
data1 = open('dallas.txt','r')
keyword = ['mavericks','stars']

In [3]:
tweets_data = []

for line in data1:
    try:
        tweet = json.loads(line)
        tweets_data.append(tweet)
    except:
        continue

In [4]:
nba_fans_location = []
nhl_fans_location = []

nba_fans_des = []
nhl_fans_des = []
test = []
for tweet in tweets_data:
    if keyword[0] in tweet['text'].lower():
        
        nba_fans_location.append(tweet['user']['location'])
        nba_fans_des.append(tweet['user']['description'])
    elif keyword[1] in tweet['text'].lower():
        test.append(tweet['text'].lower())
        nhl_fans_location.append(tweet['user']['location'])  
        nhl_fans_des.append(tweet['user']['description'])

In [6]:
# print the number of tweets
print(len(tweets_data))
print(len(nba_fans_location))
print(len(nhl_fans_location))

6891
56
46

In [5]:
# calcualte real fans
nba_real_fans = 0
nhl_real_fans = 0

for des in nba_fans_des:
    if des != None:
        if keyword[0] in des.lower():
            nba_real_fans += 1
            
for des in nhl_fans_des:
    if des != None:
        if keyword[1] in des.lower():
            nhl_real_fans += 1

print('NBA')
print(len(nba_fans_des))
print(nba_real_fans)
print(nba_real_fans*100/len(nba_fans_des))
print('NHL')
print(len(nhl_fans_des))
print(nhl_real_fans)
print(nhl_real_fans*100/len(nhl_fans_des))

NBA
0
0

ZeroDivisionError: division by zero

In [103]:
from state import *
import copy

In [104]:
# get distribution of location of fans
nba_location_count = copy.copy(states)
nhl_location_count = copy.copy(states)

for location in nba_fans_location:
    if location != None:
        temp = location.split(',')[-1].strip().upper()
        if temp in states.keys():
            nba_location_count[temp] += 1
        
for location in nhl_fans_location:
    if location != None:
        temp = location.split(',')[-1].strip().upper()
        if temp in states.keys():
            nhl_location_count[temp] += 1

In [108]:
tweets = pd.DataFrame()
tweets['NBA'] = nba_location_count.values()
tweets['NHL'] = nhl_location_count.values()
tweets['total'] = tweets.NBA + tweets.NHL
tweets.index = states.keys()

In [110]:
tweets.to_excel('phi.xls')

In [111]:
tweets

    NBA  NHL  total
OH    0    0      0
MA    6   11     17
CO    6   10     16
FL    0   14     14
DC   18   25     43
PA    0   16     16
WA    9   26     35
NV    5   15     20
AZ    2    5      7
VI   12   14     26
AS   19    9     28
NM    0    0      0
AL    1    0      1
NY    3   11     14
RI    5    8     13
NC    0    2      2
MI    4   23     27
HI    9   12     21
LA    0    0      0
TN    3    4      7
CA    0    0      0
IA   23   95    118
IN    3    1      4
KY    1    4      5
WI    1    2      3
MN    2    5      7
ME    4    4      8
OR    3    2      5
VT    0    0      0
WY    0    2      2
UT    1    1      2
AR    1   10     11
SD    0    1      1
OK    2   13     15
SC    2   11     13
MS    0    0      0
NJ   13   21     34
NA    0    0      0
GA    5   25     30
VA    7   13     20
MD    0    0      0
GU  109  339    448
KS    0    0      0
NE    1    2      3
ID    0    1      1
MO    0   11     11
TX   31  412    443
MT    0    1      1
AK    0    0      0
MP    0    0      0
CT    6    6     12
NH    0    1      1
DE    1    1      2
WV    0    3      3
ND    3    1      4
PR    0    2      2
IL   13   18     31